/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { Type } from "class-transformer";
import { StringFilter } from "../../util/StringFilter";
import { IsOptional, ValidateNested } from "class-validator";
import { ApiProperty } from "@nestjs/swagger";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { TagListRelationFilter } from "../../tag/base/TagListRelationFilter";
import { CommentListRelationFilter } from "../../comment/base/CommentListRelationFilter";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";
@InputType()
class PostWhereInput {
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  id?: StringFilter;

  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  title?: StringNullableFilter;

  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  description?: StringNullableFilter;

  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  body?: StringNullableFilter;

  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  slug?: StringNullableFilter;

  @ValidateNested()
  @Type(() => TagListRelationFilter)
  @IsOptional()
  @Field(() => TagListRelationFilter, {
    nullable: true,
  })
  @ApiProperty({
    required: false,
    type: () => TagListRelationFilter,
  })
  tags?: TagListRelationFilter;

  @ValidateNested()
  @Type(() => CommentListRelationFilter)
  @IsOptional()
  @Field(() => CommentListRelationFilter, {
    nullable: true,
  })
  @ApiProperty({
    required: false,
    type: () => CommentListRelationFilter,
  })
  comments?: CommentListRelationFilter;

  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  user?: UserWhereUniqueInput;
}
export { PostWhereInput };
